# Generated by Django 5.0.1 on 2024-02-25 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='cars',
            new_name='car',
        ),
    ]
