# Generated by Django 5.0.1 on 2024-02-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
